version: '3.8'

services:
  drupal:
    image: drupal:10
    container_name: drupal
    environment:
      - DRUPAL_DB_HOST=${DRUPAL_DB_HOST}
      - DRUPAL_DB_NAME=${DRUPAL_DB_NAME}
      - DRUPAL_DB_USER=${DRUPAL_DB_USER}
      - DRUPAL_DB_PASSWORD=${DRUPAL_DB_PASSWORD}
    volumes:
      - drupal-data:/var/www/html
    networks:
      - drupal_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - drupal_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - drupal-data:/var/www/html
    ports:
      - "80:80"
    networks:
      - drupal_network
    depends_on:
      - drupal

volumes:
  drupal-data:
  db-data:

networks:
  drupal_network:
